name: Publish Release

on:
  push:
    branches: [ automated-release-test ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Create Github Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Release Binary
        id: build
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu
          # get the mimetype of the application
          mimetype=$(file --mime-type target/x86_64-unknown-linux-gnu/release/server | cut -d':' -f2 | xargs)
          echo "::set-output name=mimetype::$mimetype"
      - name: Create Tag
        id: create_tag
        run: |
          tag=v$(cat Cargo.toml | cat Cargo.toml | grep "^version" | head -1 | sed "s/version = //" | sed "s/\"//g")-alpha
          echo "::set-output name=tag::$tag"
      - name: Delete Existing
        uses: cb80/delrel@latest
        with:
          tag: ${{steps.create_tag.outputs.tag}}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{steps.create_tag.outputs.tag}}
          release_name: ${{steps.create_tage.outputs.tag}}
          draft: true
          prerelease: false
      - name: Upload Release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/x86_64-unknown-linux-gnu/release/server
          asset_name: aether-tracker-server-x86_64-unknown-linux-gnu
          asset_content_type: ${{ steps.build.mimetype }}
      - name: Publish Release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
