name: Publish Release

on:
  push:
    branches: [ automated-release-test ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Create Github Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Release Binary
        run: cargo build --release
      - name: Create Tag
        id: create_tag
        run: |
          tag=v$(cat Cargo.toml | cat Cargo.toml | grep "^version" | head -1 | sed "s/version = //" | sed "s/\"//g")
          echo "::set-output name=tag::$tag"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{steps.create_tag.outputs.tag}}
          release_name: ${{steps.create_tage.outputs.tag}}
          draft: true
          prerelease: false

